/**
 * Inline styles for the voice agent UI.
 *
 * Separated from the page component so that the layout logic stays readable
 * and the style definitions are easy to find and edit.
 */

import type React from "react";

export const styles: Record<string, React.CSSProperties> = {
  page: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    backgroundColor: "#0f172a",
    fontFamily: "system-ui, -apple-system, sans-serif",
    color: "#e2e8f0",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "1.5rem 2rem",
    backgroundColor: "rgba(15, 23, 42, 0.8)",
    backdropFilter: "blur(12px)",
    borderBottom: "1px solid #1e293b",
    zIndex: 10,
  },
  logo: {
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
  },
  logoIcon: {
    width: "24px",
    height: "24px",
    borderRadius: "8px",
    background: "linear-gradient(135deg, #3b82f6, #8b5cf6)",
  },
  title: {
    fontSize: "1.25rem",
    fontWeight: 600,
    margin: 0,
    background: "linear-gradient(135deg, #e2e8f0, #94a3b8)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  controlPanel: {
    display: "flex",
    alignItems: "center",
    gap: "1.5rem",
  },
  statusIndicator: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  dot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    transition: "background-color 0.3s ease",
  },
  statusText: {
    fontSize: "0.875rem",
    fontWeight: 600,
    color: "#94a3b8",
    letterSpacing: "0.05em",
  },
  startButton: {
    padding: "0.75rem 1.5rem",
    borderRadius: "999px",
    border: "none",
    background: "linear-gradient(135deg, #3b82f6, #2563eb)",
    color: "white",
    fontSize: "0.875rem",
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "0 4px 14px 0 rgba(37, 99, 235, 0.39)",
    transition: "transform 0.2s, box-shadow 0.2s",
  },
  stopButton: {
    padding: "0.75rem 1.5rem",
    borderRadius: "999px",
    border: "none",
    background: "linear-gradient(135deg, #ef4444, #dc2626)",
    color: "white",
    fontSize: "0.875rem",
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "0 4px 14px 0 rgba(239, 68, 68, 0.39)",
    transition: "transform 0.2s, box-shadow 0.2s",
  },
  main: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    padding: "2rem",
    overflow: "hidden",
    position: "relative",
  },
  chatContainer: {
    flex: 1,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "1.5rem",
    paddingBottom: "4rem",
    maxWidth: "800px",
    margin: "0 auto",
    width: "100%",
    scrollbarWidth: "none",
  },
  emptyState: {
    margin: "auto",
    textAlign: "center",
    color: "#64748b",
  },
  messageWrapper: {
    display: "flex",
    width: "100%",
    animation: "fadeIn 0.3s ease",
  },
  userMessage: {
    maxWidth: "80%",
    padding: "1rem 1.25rem",
    borderRadius: "1.5rem",
    borderBottomRightRadius: "0.5rem",
    backgroundColor: "#1e293b",
    color: "#f8fafc",
    fontSize: "1rem",
    lineHeight: 1.5,
    boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
  },
  botMessage: {
    maxWidth: "80%",
    padding: "1rem 1.25rem",
    borderRadius: "1.5rem",
    borderBottomLeftRadius: "0.5rem",
    background: "linear-gradient(135deg, rgba(59, 130, 246, 0.1), rgba(139, 92, 246, 0.1))",
    border: "1px solid rgba(59, 130, 246, 0.2)",
    color: "#f8fafc",
    fontSize: "1rem",
    lineHeight: 1.5,
    backdropFilter: "blur(8px)",
  },
  interimMessage: {
    opacity: 0.6,
    borderStyle: "dashed",
    borderWidth: "1px",
    borderColor: "#475569",
  },
  speakingIndicator: {
    position: "absolute",
    bottom: "2rem",
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
    padding: "0.75rem 1.5rem",
    backgroundColor: "rgba(30, 41, 59, 0.9)",
    backdropFilter: "blur(12px)",
    borderRadius: "999px",
    border: "1px solid rgba(59, 130, 246, 0.3)",
    color: "#93c5fd",
    fontSize: "0.875rem",
    fontWeight: 500,
    boxShadow: "0 10px 15px -3px rgba(0, 0, 0, 0.2), 0 0 20px rgba(59, 130, 246, 0.15)",
    zIndex: 20,
  },
  canvas: {
    borderRadius: "6px",
  },
};
